### ISSUE TITLE
Fork off subshells

### ISSUE THREAD

**Issue by BradleyCai** [ammongit/rshell#14]
Right now `{ }` and `( )` are treated the same. When running `( )` (aka subshells) they need to actually making a sub-shell. Fork off before running depending on the value of the `subshell` field.

**Comment by ammongit** [comment]
See #28 for more information. Especially [`command.c`](https://github.com/ammongit/rshell/blob/bg-processes/src/command.c)

**Comment by ammongit** [comment]
Fixed in #28 (and #44)
