### ISSUE TITLE
Add "test" builtin (aka "[")

### ISSUE THREAD

**Issue by ammongit** [ammongit/rshell#20]
Assignment 3 has us create the `test` and `[` builtins. These in fact perform the same functionality, except that if `argv[0]` is `[`, it expects `]` as the last argument.

The default behavior should be `-e`, not `-n`

This builtin should also print out its return value, by outputing either `(True)` or `(False)`.

**Comment by BradleyCai** [comment]
We need to support the following options:

* `-e` - path exists
* `-d` - directory exists
* `-f` - file exists
The default behavior should be `-e`, not `-n`

We could support the following options:
* `-n` - string is not empty
* `-z` - string is zero length (i.e. empty)
* `!` - invert result
* `=` or `==` - string equality
* `!=` - string inequality
* `-eq`, `-ne`, `-lt`, `-le`, `-gt`, `-ge` - integer comparisons

**Comment by BradleyCai** [comment]
Fixed in #34
